# Generated by Django 5.1.6 on 2025-02-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '全員公開'), ('members', 'ファンクラブ限定'), ('private', '非公開')], default='public', max_length=10),
        ),
    ]
