# Generated by Django 5.1.6 on 2025-02-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '全員公開'), ('members', 'ファンクラブ限定'), ('draft', '下書き'), ('private', '非公開')], default='public', max_length=10),
        ),
    ]
