# Generated by Django 5.1.6 on 2025-02-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_publish_at_post_visibility_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='member_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
