# Generated by Django 5.1.6 on 2025-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('draft', '下書き'), ('members', 'メンバー限定'), ('public', '全員公開'), ('unlisted', '限定公開（URLでのみ閲覧可能）')], default='draft', max_length=10),
        ),
    ]
