# Generated by Django 5.1.6 on 2025-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_member_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('draft', '下書き'), ('members', 'メンバー限定'), ('public', '全員公開'), ('unlisted', '限定公開（URLでのみ閲覧可能）')], default='druft', max_length=10),
        ),
    ]
